### PR TITLE
Add new product(s): products/cboard.json

### PR DESCRIPTION
**Pull request by lacabra**
Add new product(s) from [unicef/publicgoods-candidates](https://github.com/unicef/publicgoods/candidates)

### CODE REVIEW

**Review by conradsp — CHANGES_REQUESTED** [review]
This is a duplicate of Cireha. We should rename Cireha too cboard (product) with Cireha as the org.

**Comment by nathanbaleeta** [comment]
@conradsp and @lacabra the repo regards ( ) as unexpected tokens. Probably "cboard project" would pass.

**Comment by lacabra** [comment]
@nathanbaleeta just use `cboard` as the name

**Review by conradsp — CHANGES_REQUESTED** [review]
We could keep UNICEF Ventures Fund as a funding organization and CIREHA as the owner.

**Review by conradsp — APPROVED** [review]

**Pull request merged**
