### PR TITLE
Add new product(s): products/ai-powered-poverty-estimation.json

### PR DESCRIPTION
**Pull request by lacabra**
Add new product(s) from [unicef/publicgoods-candidates](https://github.com/unicef/publicgoods/candidates)

### CODE REVIEW

**Comment by lacabra** [comment]
@conradsp: This PR fails because it's the first `AI model` we are indexing. As you may recall the Secretary General includes "AI Models" in their definition of digital public goods, and we had them listed in our definition, but never coded it into the data schema. We just [updated](https://github.com/unicef/publicgoods-candidates/pull/109/commits/0e6b29a4553694be8535f798f11d64fc6902c5d3) our own schema, and I will proceed to submit a PR to the products-schema repo, if it's ok with you?

**Comment by conradsp** [comment]
> @conradsp: This PR fails because it's the first `AI model` we are indexing. As you may recall the Secretary General includes "AI Models" in their definition of digital public goods, and we had them listed in our definition, but never coded it into the data schema. We just [updated](https://github.com/unicef/publicgoods-candidates/pull/109/commits/0e6b29a4553694be8535f798f11d64fc6902c5d3) our own schema, and I will proceed to submit a PR to the products-schema repo, if it's ok with you?

Yes that makes sense to me. Will look for the PR in products-schema.

**Review by conradsp — CHANGES_REQUESTED** [review]
@lacabra - I have merged the changes to the product schema. If you can pull that change over to this repo, I can approve and merge this PR.

**Comment by lacabra** [comment]
@conradsp: merged the new data-schema, the CI is passing. Ready for your review 🙏

**Review by conradsp — APPROVED** [review]

**Pull request merged**
